project:
  type: book
  output-dir: docs

book:
  title: "Exploratory Analysis of Bayesian Models"
  author: "ArviZ-devs"
  date: today
  favicon: favicon.ico

  chapters:
    - index.qmd
    - Chapters/Elements_of_visualization.qmd
    - Chapters/DataTree.qmd
    - Chapters/Distributions.qmd
    - Chapters/MCMC_diagnostics.qmd
    - Chapters/Model_criticism.qmd
    - Chapters/Model_comparison.qmd
    - Chapters/Case_study_model_comparison.qmd
    - Chapters/Presenting_results.qmd
    - Chapters/References.qmd

  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        text: github
        menu:
          - text: source
            url:  https://github.com/arviz-devs/Exploratory-Analysis-of-Bayesian-Models
          - text: issues
            url:  https://github.com/arviz-devs/Exploratory-Analysis-of-Bayesian-Models/issues/new
      - icon: coin
        href: https://numfocus.org/donate-to-arviz 
        text: donations

format:
  html:
    toc: true
    code-line-numbers: true
    number-sections: true
    number-offset: -1


theme:
  light: cosmo
  dark: darkly

bibliography: references.bib

google-scholar: true
