project:
  type: book
  output-dir: docs

book:
  title: "Exploratory Analysis of Bayesian Models"
  author:
    - name: Osvaldo A. Martin 
      url: https://aloctavodia.github.io/
      orcid: 0000-0001-7419-8978
      affiliations:
        - name: Aalto University
          affiliation-url: https://research.cs.aalto.fi/pml/
          address: Otakaari 24, 02150
          city: Espoo
          country: Finland
          postal-code: 02150
        - name: UNSAM
          affiliation-url: https://unsam.edu.ar/escuelas/ecyt/661/ciencia/ciencia-de-datos
          address: Campus Miguelete, 25 de Mayo y Francia
          city: Buenos Aires
          country: Argentina
          postal-code: 1650
    - name: Oriol Abril-Pla 
      url: https://oriolabrilpla.cat/en/index.html
      affiliation: ArviZ
      affiliation-url: https://github.com/arviz-devs
      orcid: https://orcid.org/0000-0002-1847-9481
      city: Barcelona
      country: Spain
    - name: ArviZ-devs
      url: https://github.com/arviz-devs
  date: today
  favicon: favicon.ico

  chapters:
    - index.qmd
    - Chapters/Elements_of_visualization.qmd
    - Chapters/DataTree.qmd
    - Chapters/Distributions.qmd
    - Chapters/MCMC_diagnostics.qmd
    - Chapters/Model_criticism.qmd
    - Chapters/Model_comparison.qmd
    - Chapters/Case_study_model_comparison.qmd
    - Chapters/Variable_selection.qmd
    - Chapters/Prior_elicitation.qmd
    - Chapters/Presenting_results.qmd
    - Chapters/Bayesian_workflow.qmd
    - Chapters/References.qmd

  page-navigation: true
  reader-mode: true
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        text: github
        menu:
          - text: source
            url:  https://github.com/arviz-devs/Exploratory-Analysis-of-Bayesian-Models
          - text: issues
            url:  https://github.com/arviz-devs/Exploratory-Analysis-of-Bayesian-Models/issues/new
      - icon: coin
        href: https://numfocus.org/donate-to-arviz 
        text: donations

format:
  html:
    toc: true
    code-line-numbers: true
    number-sections: true
    number-offset: -1


theme:
  light: cosmo
  dark: darkly

bibliography: references.bib

google-scholar: true
